/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'Webonise' at '17/3/16 1:58 PM' with Gradle 2.3
 *
 * @author Webonise, @date 17/3/16 1:58 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
