/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'Webonise' at '17/3/16 1:58 PM' with Gradle 2.3
 *
 * @author Webonise, @date 17/3/16 1:58 PM
 */


import org.kaddiya.grorchestrator.Grorchestrator
import spock.lang.Specification

class GrorchestratorTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Grorchestrator lib = new Grorchestrator()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
