/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'Webonise' at '17/3/16 1:58 PM' with Gradle 2.3
 *
 * @author Webonise, @date 17/3/16 1:58 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
